Notebook Version: 0.1

# Project
NFL Front Office Decision Support System

## Sprint
Sprint 2

## Notebook
01_Data_Source_Validation.ipynb

## Author(s)
Bill Reed
Jason Kuzmission

## Date
07/17/27

## Status
Completed

## Objective

Determine whether publicly available NFL datasets contain sufficient, reliable, and reproducible information to support the development of a machine learning model that predicts future wide receiver performance for NFL contract and roster decision support.

# Data Source Inventory

Before downloading any data, we will inventory the datasets available through nflreadpy and evaluate whether they contain the information necessary to answer our research question.

The purpose of this section is to understand the available data rather than begin analysis.

Reference:
https://nflreadr.nflverse.com/articles/dictionary_player_stats.html

In [66]:
# Install required project packages
%pip install nflreadpy

Requirement already satisfied: nflreadpy in /opt/anaconda3/lib/python3.13/site-packages (0.1.5)
Requirement already satisfied: requests>=2.28.0 in /opt/anaconda3/lib/python3.13/site-packages (from nflreadpy) (2.32.3)
Requirement already satisfied: polars>=0.20.0 in /opt/anaconda3/lib/python3.13/site-packages (from nflreadpy) (1.42.1)
Requirement already satisfied: platformdirs>=3.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from nflreadpy) (4.3.7)
Requirement already satisfied: tqdm>=4.64.0 in /opt/anaconda3/lib/python3.13/site-packages (from nflreadpy) (4.67.1)
Requirement already satisfied: pydantic>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from nflreadpy) (2.10.3)
Requirement already satisfied: pydantic-settings>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from nflreadpy) (2.6.1)
Requirement already satisfied: polars-runtime-32==1.42.1 in /opt/anaconda3/lib/python3.13/site-packages (from polars>=0.20.0->nflreadpy) (1.42.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic>=2.0.0->nflreadpy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic>=2.0.0->nflreadpy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic>=2.0.0->nflreadpy) (4.12.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.28.0->nflreadpy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.28.0->nflreadpy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.28.0->nflreadpy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.28.0->nflreadpy) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [67]:
import nflreadpy as nfl
import pandas as pd

pd.set_option("display.max_columns", None)

print("Environment ready.")

Environment ready.

In [68]:
functions = sorted([f for f in dir(nfl) if f.startswith("load")])

print(f"Total load functions: {len(functions)}\n")

for f in functions:
    print(f)

Total load functions: 25

load_combine
load_contracts
load_depth_charts
load_draft_picks
load_ff_opportunity
load_ff_playerids
load_ff_rankings
load_ffverse
load_ftn_charting
load_injuries
load_nextgen_stats
load_officials
load_participation
load_pbp
load_pfr_advstats
load_player_stats
load_players
load_rosters
load_rosters_weekly
load_schedules
load_snap_counts
load_stats
load_team_stats
load_teams
load_trades

In [69]:
help(nfl.load_player_stats)

Help on function load_player_stats in module nflreadpy.load_stats:

load_player_stats(
    seasons: int | list[int] | bool | None = None,
    summary_level: Literal['week', 'reg', 'post', 'reg+post'] = 'week'
) -> polars.dataframe.frame.DataFrame
    Load NFL player statistics.

    Args:
        seasons: Season(s) to load. If None, loads current season.
                If True, loads all available data.
                If int or list of ints, loads specified season(s).
        summary_level: Summary level ("week", "reg", "post", "reg+post").

    Returns:
        Polars DataFrame with player statistics.

    See Also:
        <https://nflreadr.nflverse.com/reference/load_player_stats.html>

    Data Dictionary:
        <https://nflreadr.nflverse.com/articles/dictionary_player_stats.html>

## Findings

The `load_player_stats()` function supports loading one season, multiple seasons, or all available seasons. Data can be returned at the weekly, regular season, postseason, or combined summary levels.

Although the function returns a Polars DataFrame, it can be converted to a pandas DataFrame so the remainder of the project can use the tools already covered in this course.

The function is well documented and includes an official data dictionary, increasing transparency and reproducibility.

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.to_pandas.html

In [70]:
player_stats = nfl.load_player_stats(
    seasons=2024,
    summary_level="reg"
)

In [71]:
type(player_stats)

polars.dataframe.frame.DataFrame

In [72]:
[m for m in dir(player_stats) if "pandas" in m.lower()]

['_from_pandas',
 '_to_pandas_with_object_columns',
 '_to_pandas_without_object_columns',
 'to_pandas']

In [73]:
player_stats_pd = player_stats.to_pandas()

In [74]:
player_stats.shape

(1997, 143)

In [75]:
player_stats.head()

shape: (5, 143)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 256.58    ┆ 256.58    │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002424 ┆ M.Lewis   ┆ Marcedes  ┆ TE       ┆ … ┆ 0         ┆ 0         ┆ 0.2       ┆ 1.2       │
│ 3         ┆           ┆ Lewis     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002602 ┆ J.Jansen  ┆ J.J.      ┆ LS       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 7         ┆           ┆ Jansen    ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [76]:
type(player_stats.columns)

list

In [77]:
player_stats["position"].unique()

shape: (26,)
Series: 'position' [str]
[
	"OT"
	"FB"
	"CB"
	"NT"
	"OL"
	…
	"G"
	"MLB"
	"C"
	"K"
	"DE"
]

In [78]:
player_stats.filter(
    player_stats["position"] == "WR"
).shape

(235, 143)

In [79]:
for column in player_stats.columns:
    print(column)

player_id
player_name
player_display_name
position
position_group
headshot_url
season
season_type
recent_team
games
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
wopr
special_teams_tds
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds
penalties
penalty_yards
fumbles_forced_by_opp
fumbles_not_forced
fumbles_out_of_bounds
fumbles_total
fumbles_lost_total
punt_returns
punt_return_yards
kickoff_returns
kickoff_return_yards
fg_made
fg_att
fg_missed
fg_blocked
fg_long
fg_pct
fg_made_0_19
fg_made_20_29
fg_made_30_39
fg_made_40_49
fg_made_50_59
fg_made_60_
fg_missed_0_19
fg_missed_20_29
fg_missed_30_39
fg_missed_40_49
fg_missed_50_59
fg_missed_60_
fg_made_list
fg_missed_list
fg_blocked_list
fg_made_distance
fg_missed_distance
fg_blocked_distance
pat_made
pat_att
pat_missed
pat_blocked
pat_pct
gwfg_made
gwfg_att
gwfg_missed
gwfg_blocked
gwfg_distance_list
pt_att
pt_blocked
pt_long
pt_yards
pt_inside_20
pt_out_of_bounds
pt_downed
pt_touchback
pt_fair_caught
pt_returned
pt_return_yards
pt_return_tds
pt_net_yards
fantasy_points
fantasy_points_ppr

In [80]:
# Find every column related to receiving
receiving_columns = [
    col for col in player_stats.columns
    if "receiv" in col.lower()
]

receiving_columns

['receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'receiving_10',
 'receiving_16',
 'receiving_20',
 'receiving_40']

In [81]:
passing_columns = [
    col for col in player_stats.columns
    if "pass" in col.lower()
]

passing_columns

['passing_yards',
 'passing_tds',
 'passing_interceptions',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'def_pass_defended']

In [82]:
rushing_columns = [
    col for col in player_stats.columns
    if "rush" in col.lower()
]

rushing_columns

['rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40']

In [83]:
fantasy_columns = [
    col for col in player_stats.columns
    if "fantasy" in col.lower()
]

fantasy_columns

['fantasy_points', 'fantasy_points_ppr']

# Data Dictionary Validation

## Objective

We have confirmed that nflreadpy loads player statistics successfully. The next step is to validate whether the available variables support the research question.

Next step, is to identify variables that are directly related to predicting future wide receiver performance. These variables will become more important for later analysis and model development.

### Source

NFLverse Player Statistics Data Dictionary
https://nflreadr.nflverse.com/articles/dictionary_player_stats.html

# External Data Source Evaluation

## Objective

nflreadpy provides comprehensive player performance statistics, our research question also requires contract information to evaluate player value relative to salary.

# Contract Dataset Validation

## Objective

Determine whether the contract data available through nflreadpy contain enough financial information to support NFL wide receiver contract and roster decisions.

## Questions

1. What contract variables are available?
2. Does the dataset contain wide receivers?
3. Can the contract records be linked to player statistics?
4. Is the historical information sufficient for this project?

## Source

The nflreadpy contract data originate from the nflverse contract dataset, which is based on historical contract information from OverTheCap.

Official references:

nflverse contract data dictionary

In [84]:
help(nfl.load_contracts)

Help on function load_contracts in module nflreadpy.load_contracts:

load_contracts() -> polars.dataframe.frame.DataFrame
    Load NFL historical contract data.

    Returns:
        Polars DataFrame with historical contract information including        player details, contract terms, values, and team information.

    See Also:
        <https://nflreadr.nflverse.com/reference/load_contracts.html>

    Data Dictionary:
        <https://nflreadr.nflverse.com/articles/dictionary_contracts.html>

In [85]:
print(nfl.load_contracts.__doc__)

Load NFL historical contract data.

Returns:
    Polars DataFrame with historical contract information including        player details, contract terms, values, and team information.

See Also:
    <https://nflreadr.nflverse.com/reference/load_contracts.html>

Data Dictionary:
    <https://nflreadr.nflverse.com/articles/dictionary_contracts.html>

In [86]:
contracts = nfl.load_contracts()

In [87]:
type(contracts)

polars.dataframe.frame.DataFrame

In [88]:
contracts.shape

(51711, 25)

In [89]:
contracts.head()

shape: (5, 25)
┌────────────┬──────────┬─────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player     ┆ position ┆ team    ┆ is_active ┆ … ┆ draft_roun ┆ draft_ove ┆ draft_tea ┆ cols      │
│ ---        ┆ ---      ┆ ---     ┆ ---       ┆   ┆ d          ┆ rall      ┆ m         ┆ ---       │
│ str        ┆ str      ┆ str     ┆ bool      ┆   ┆ ---        ┆ ---       ┆ ---       ┆ list[stru │
│            ┆          ┆         ┆           ┆   ┆ i32        ┆ i32       ┆ str       ┆ ct[13]]   │
╞════════════╪══════════╪═════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Joe Burrow ┆ QB       ┆ Bengals ┆ true      ┆ … ┆ 1          ┆ 1         ┆ Bengals   ┆ [{"2020", │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ "Bengals" │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ ,0.61,5.9 │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ 700…      │
│ Aaron      ┆ QB       ┆ GB/NYJ  ┆ false     ┆ … ┆ 1          ┆ 24        ┆ Packers   ┆ [{"2005", │
│ Rodgers    ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ "Packers" │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ ,0.23,0.3 │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ ,0.…      │
│ Josh Allen ┆ QB       ┆ Bills   ┆ false     ┆ … ┆ 1          ┆ 7         ┆ Bills     ┆ [{"2018", │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ "Bills",0 │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ .48,3.371 │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ 461…      │
│ Russell    ┆ QB       ┆ Broncos ┆ false     ┆ … ┆ 3          ┆ 75        ┆ Seahawks  ┆ [{"2012", │
│ Wilson     ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ "Seahawks │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ ",0.39,0. │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ 154…      │
│ Dak        ┆ QB       ┆ Cowboys ┆ true      ┆ … ┆ 4          ┆ 135       ┆ Cowboys   ┆ [{"2016", │
│ Prescott   ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ "Cowboys" │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ ,0.45,0.0 │
│            ┆          ┆         ┆           ┆   ┆            ┆           ┆           ┆ 958…      │
└────────────┴──────────┴─────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [90]:
contracts.columns

['player',
 'position',
 'team',
 'is_active',
 'year_signed',
 'years',
 'value',
 'apy',
 'guaranteed',
 'apy_cap_pct',
 'inflated_value',
 'inflated_apy',
 'inflated_guaranteed',
 'player_page',
 'otc_id',
 'gsis_id',
 'date_of_birth',
 'height',
 'weight',
 'college',
 'draft_year',
 'draft_round',
 'draft_overall',
 'draft_team',
 'cols']

In [91]:
expected_contract_columns = [
    "player",
    "position",
    "team",
    "is_active",
    "year_signed",
    "years",
    "value",
    "apy",
    "guaranteed"
]

for column in expected_contract_columns:
    print(f"{column}: {column in contracts.columns}")

player: True
position: True
team: True
is_active: True
year_signed: True
years: True
value: True
apy: True
guaranteed: True

In [92]:
wr_contracts = contracts.filter(
    contracts["position"] == "WR"
)

wr_contracts.shape

(7510, 25)

In [93]:
wr_contracts.select([
    "player",
    "position",
    "team",
    "year_signed",
    "years",
    "value",
    "apy",
    "guaranteed",
    "is_active"
]).head(10)

shape: (10, 9)
┌────────────┬──────────┬───────────┬────────────┬───┬────────┬───────────┬────────────┬───────────┐
│ player     ┆ position ┆ team      ┆ year_signe ┆ … ┆ value  ┆ apy       ┆ guaranteed ┆ is_active │
│ ---        ┆ ---      ┆ ---       ┆ d          ┆   ┆ ---    ┆ ---       ┆ ---        ┆ ---       │
│ str        ┆ str      ┆ str       ┆ ---        ┆   ┆ f64    ┆ f64       ┆ f64        ┆ bool      │
│            ┆          ┆           ┆ i32        ┆   ┆        ┆           ┆            ┆           │
╞════════════╪══════════╪═══════════╪════════════╪═══╪════════╪═══════════╪════════════╪═══════════╡
│ Ja'Marr    ┆ WR       ┆ Bengals   ┆ 2025       ┆ … ┆ 161.0  ┆ 40.25     ┆ 73.9       ┆ true      │
│ Chase      ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ Tyreek     ┆ WR       ┆ Dolphins  ┆ 2022       ┆ … ┆ 120.0  ┆ 30.0      ┆ 52.535     ┆ false     │
│ Hill       ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ Jerry Rice ┆ WR       ┆ 49ers     ┆ 1996       ┆ … ┆ 29.0   ┆ 5.8       ┆ 4.0        ┆ false     │
│ Jaxon Smit ┆ WR       ┆ Seahawks  ┆ 2026       ┆ … ┆ 168.6  ┆ 42.15     ┆ 69.130996  ┆ true      │
│ h-Njigba   ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ DeAndre    ┆ WR       ┆ Cardinals ┆ 2020       ┆ … ┆ 54.5   ┆ 27.25     ┆ 42.75      ┆ false     │
│ Hopkins    ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ Justin     ┆ WR       ┆ Vikings   ┆ 2024       ┆ … ┆ 140.0  ┆ 35.0      ┆ 88.743     ┆ true      │
│ Jefferson  ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ Randy Moss ┆ WR       ┆ Vikings   ┆ 2001       ┆ … ┆ 63.536 ┆ 9.076571  ┆ 10.0       ┆ false     │
│ Davante    ┆ WR       ┆ LV/NYJ    ┆ 2022       ┆ … ┆ 140.0  ┆ 28.0      ┆ 22.75      ┆ false     │
│ Adams      ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ Calvin     ┆ WR       ┆ Lions     ┆ 2012       ┆ … ┆ 113.45 ┆ 16.207143 ┆ 48.75      ┆ false     │
│ Johnson    ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
│ Larry      ┆ WR       ┆ Cardinals ┆ 2011       ┆ … ┆ 113.0  ┆ 16.142857 ┆ 20.0       ┆ false     │
│ Fitzgerald ┆          ┆           ┆            ┆   ┆        ┆           ┆            ┆           │
└────────────┴──────────┴───────────┴────────────┴───┴────────┴───────────┴────────────┴───────────┘

In [94]:
shared_columns = sorted(
    set(player_stats.columns) &
    set(contracts.columns)
)

shared_columns

['position']

In [95]:
id_columns = [
    col for col in player_stats.columns
    if "id" in col.lower()
]

id_columns

['player_id', 'pt_inside_20']

In [96]:
name_columns = [
    col for col in player_stats.columns
    if "name" in col.lower()
]

name_columns

['player_name', 'player_display_name']

In [97]:
team_columns = [
    col for col in player_stats.columns
    if "team" in col.lower()
    ]

team_columns

['recent_team', 'special_teams_tds']

In [98]:
players = nfl.load_players()

players.shape

(25033, 39)

In [99]:
players.columns

['gsis_id',
 'display_name',
 'common_first_name',
 'first_name',
 'last_name',
 'short_name',
 'football_name',
 'suffix',
 'esb_id',
 'nfl_id',
 'pfr_id',
 'pff_id',
 'otc_id',
 'espn_id',
 'smart_id',
 'birth_date',
 'position_group',
 'position',
 'ngs_position_group',
 'ngs_position',
 'height',
 'weight',
 'headshot',
 'college_name',
 'college_conference',
 'jersey_number',
 'rookie_season',
 'last_season',
 'latest_team',
 'status',
 'ngs_status',
 'ngs_status_short_description',
 'years_of_experience',
 'pff_position',
 'pff_status',
 'draft_year',
 'draft_round',
 'draft_pick',
 'draft_team']

In [100]:
players.head()

shape: (5, 39)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gsis_id   ┆ display_n ┆ common_fi ┆ first_nam ┆ … ┆ draft_yea ┆ draft_rou ┆ draft_pic ┆ draft_te │
│ ---       ┆ ame       ┆ rst_name  ┆ e         ┆   ┆ r         ┆ nd        ┆ k         ┆ am       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ i32       ┆ i32       ┆ i32       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 00-002883 ┆ Isaako    ┆ Isaako    ┆ Isaako    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0         ┆ Aaitui    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00-003838 ┆ Israel    ┆ Israel    ┆ Israel    ┆ … ┆ 2023      ┆ 5         ┆ 143       ┆ NYJ      │
│ 9         ┆ Abanikand ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ a         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00-002464 ┆ Jon       ┆ Jon       ┆ Jon       ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 4         ┆ Abbate    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ABB498348 ┆ Vince     ┆ Vince     ┆ Vincent   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ Abbott    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00-003102 ┆ Jared Abb ┆ Jared     ┆ Jared     ┆ … ┆ 2014      ┆ 5         ┆ 176       ┆ GB       │
│ 1         ┆ rederis   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Identifier Validation

The next step is to verify that the player identifiers are consistent across the player statistics, player metadata, and contract datasets.

In [101]:
players.select([
    "gsis_id",
    "display_name",
    "nfl_id",
    "pfr_id",
    "espn_id"
]).head(10)

shape: (10, 5)
┌────────────┬───────────────────┬────────┬────────────┬─────────┐
│ gsis_id    ┆ display_name      ┆ nfl_id ┆ pfr_id     ┆ espn_id │
│ ---        ┆ ---               ┆ ---    ┆ ---        ┆ ---     │
│ str        ┆ str               ┆ str    ┆ str        ┆ str     │
╞════════════╪═══════════════════╪════════╪════════════╪═════════╡
│ 00-0028830 ┆ Isaako Aaitui     ┆ null   ┆ AaitIs00   ┆ 14856   │
│ 00-0038389 ┆ Israel Abanikanda ┆ 56008  ┆ AbanIs00   ┆ 4429202 │
│ 00-0024644 ┆ Jon Abbate        ┆ null   ┆ null       ┆ null    │
│ ABB498348  ┆ Vince Abbott      ┆ null   ┆ abbotvin01 ┆ null    │
│ 00-0031021 ┆ Jared Abbrederis  ┆ 41405  ┆ AbbrJa00   ┆ 16836   │
│ 00-0032860 ┆ Mehdi Abdesmad    ┆ 43927  ┆ AbdeMe00   ┆ 2576467 │
│ 00-0028564 ┆ Isa Abdul-Quddus  ┆ 38044  ┆ AbduIs00   ┆ 14466   │
│ 00-0032104 ┆ Ameer Abdullah    ┆ 42397  ┆ AbduAm00   ┆ 2576336 │
│ 00-0023663 ┆ Hamza Abdullah    ┆ 30059  ┆ AbduHa20   ┆ 8645    │
│ 00-0025940 ┆ Husain Abdullah   ┆ 33465  ┆ AbduHu99   ┆ 11910   │
└────────────┴───────────────────┴────────┴────────────┴─────────┘

In [102]:
player_stats.select([
    "player_id",
    "player_name",
    "player_display_name",
    "recent_team"
]).head(10)

shape: (10, 4)
┌────────────┬─────────────┬─────────────────────┬─────────────┐
│ player_id  ┆ player_name ┆ player_display_name ┆ recent_team │
│ ---        ┆ ---         ┆ ---                 ┆ ---         │
│ str        ┆ str         ┆ str                 ┆ str         │
╞════════════╪═════════════╪═════════════════════╪═════════════╡
│ 00-0023459 ┆ A.Rodgers   ┆ Aaron Rodgers       ┆ NYJ         │
│ 00-0023853 ┆ M.Prater    ┆ Matt Prater         ┆ ARI         │
│ 00-0024243 ┆ M.Lewis     ┆ Marcedes Lewis      ┆ CHI         │
│ 00-0025565 ┆ N.Folk      ┆ Nick Folk           ┆ TEN         │
│ 00-0026027 ┆ J.Jansen    ┆ J.J. Jansen         ┆ CAR         │
│ 00-0026158 ┆ J.Flacco    ┆ Joe Flacco          ┆ IND         │
│ 00-0026190 ┆ C.Campbell  ┆ Calais Campbell     ┆ MIA         │
│ 00-0026300 ┆ J.Johnson   ┆ Josh Johnson        ┆ BAL         │
│ 00-0026498 ┆ M.Stafford  ┆ Matthew Stafford    ┆ LA          │
│ 00-0026858 ┆ G.Gano      ┆ Graham Gano         ┆ NYG         │
└────────────┴─────────────┴─────────────────────┴─────────────┘

In [103]:
import polars as pl

In [104]:
players.filter(
    pl.col("display_name") == "Aaron Rodgers"
).select([
    "display_name",
    "gsis_id",
    "nfl_id",
    "pfr_id"
])

shape: (1, 4)
┌───────────────┬────────────┬────────┬──────────┐
│ display_name  ┆ gsis_id    ┆ nfl_id ┆ pfr_id   │
│ ---           ┆ ---        ┆ ---    ┆ ---      │
│ str           ┆ str        ┆ str    ┆ str      │
╞═══════════════╪════════════╪════════╪══════════╡
│ Aaron Rodgers ┆ 00-0023459 ┆ 29851  ┆ RodgAa00 │
└───────────────┴────────────┴────────┴──────────┘

In [105]:
contracts.filter(
    pl.col("player").str.contains("Rodgers", literal=True)
).select([
    "player",
    "gsis_id",
    "team",
    "position",
    "year_signed"
])

shape: (64, 5)
┌─────────────────────────────┬────────────┬────────────┬──────────┬─────────────┐
│ player                      ┆ gsis_id    ┆ team       ┆ position ┆ year_signed │
│ ---                         ┆ ---        ┆ ---        ┆ ---      ┆ ---         │
│ str                         ┆ str        ┆ str        ┆ str      ┆ i32         │
╞═════════════════════════════╪════════════╪════════════╪══════════╪═════════════╡
│ Aaron Rodgers               ┆ 00-0023459 ┆ GB/NYJ     ┆ QB       ┆ 2022        │
│ Aaron Rodgers               ┆ 00-0023459 ┆ Packers    ┆ QB       ┆ 2018        │
│ Aaron Rodgers               ┆ 00-0023459 ┆ Packers    ┆ QB       ┆ 2013        │
│ Aaron Rodgers               ┆ 00-0023459 ┆ Jets       ┆ QB       ┆ 2023        │
│ Aaron Rodgers               ┆ 00-0023459 ┆ Packers    ┆ QB       ┆ 2008        │
│ …                           ┆ …          ┆ …          ┆ …        ┆ …           │
│ Dominique Rodgers-Cromartie ┆ 00-0026156 ┆ Raiders    ┆ CB       ┆ 2018        │
│ Dominique Rodgers-Cromartie ┆ 00-0026156 ┆ Commanders ┆ CB       ┆ 2019        │
│ Isaiah Rodgers              ┆ 00-0036222 ┆ Eagles     ┆ CB       ┆ 2023        │
│ Isaiah Rodgers              ┆ 00-0036222 ┆ Colts      ┆ CB       ┆ 2020        │
│ Kacy Rodgers                ┆ null       ┆ Jets       ┆ S        ┆ 2018        │
└─────────────────────────────┴────────────┴────────────┴──────────┴─────────────┘

## Validation Summary

The player identifiers were successfully validated across the three primary datasets.

Validated relationship:

player_stats.player_id
        │
        ▼
players.gsis_id
        │
        ▼
contracts.gsis_id

This confirms that the datasets can be joined using the GSIS player identifier and provides the foundation for the integrated modeling dataset used in subsequent notebooks.

## Data Cleaning

Before we begin initial data exploration, we must make sure we have clean data to test and most importantly, we need to join our player stats data with our contract data so we can understand the full scope of the task at hand.

## Player Stats Cleaning

We will need to make sure there are no empty rows, missing GSIS IDs, check missing or invalid values, as well as gte a subset of Wide Receiver Stats to prepare for joining the data. The most notable of these is the missing GSIS ID or else we will be missing a full players stats or even worse, won't be able to join the data successfully

In [106]:
# Confirm that the existing objects are available

print("Player statistics:", player_stats.shape)
print("Player metadata:", players.shape)
print("WR contracts:", wr_contracts.shape)

Player statistics: (1997, 143)
Player metadata: (25033, 39)
WR contracts: (7510, 25)

In [107]:
# Confirm that the player_id and gsis_id columns are of the same type

print("player_stats.player_id type:")
print(player_stats.schema["player_id"])

print("\nplayers.gsis_id type:")
print(players.schema["gsis_id"])

print("\nwr_contracts.gsis_id type:")
print(wr_contracts.schema["gsis_id"])

player_stats.player_id type:
String

players.gsis_id type:
String

wr_contracts.gsis_id type:
String

In [108]:
# Create the subset for WR player statistics

wr_player_stats = player_stats.filter(
    pl.col("position") == "WR"
)

print("WR player-stat rows:", wr_player_stats.height)

WR player-stat rows: 235

In [109]:
# Select the columns of interest for WR player statistics

wr_player_stats = wr_player_stats.select([
    "player_id",
    "player_name",
    "player_display_name",
    "position",
    "season",
    "season_type",
    "recent_team",
    "games",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_epa",
    "receiving_2pt_conversions",
    "receiving_10",
    "receiving_16",
    "receiving_20",
    "receiving_40",
    "racr",
    "target_share",
    "air_yards_share",
    "wopr",
    "fantasy_points",
    "fantasy_points_ppr"
])

In [110]:
# Renaming player_id to gsis_id to match the other dataframes for merging

wr_player_stats = wr_player_stats.rename({
    "player_id": "gsis_id"
})

In [111]:
# Remove rows with null or empty gsis_id values to ensure data integrity

wr_player_stats = wr_player_stats.filter(
    pl.col("gsis_id").is_not_null() &
    (pl.col("gsis_id").str.strip_chars() != "")
)

In [112]:
# Standardizing the gsis_id column by stripping any leading or trailing whitespace characters

wr_player_stats = wr_player_stats.with_columns(
    pl.col("gsis_id")
      .str.strip_chars()
      .alias("gsis_id")
)

In [113]:
# Checking for duplicate player-season combinations in the WR player statistics

player_stats_duplicates = (
    wr_player_stats
    .group_by(["gsis_id", "season"])
    .len()
    .filter(pl.col("len") > 1)
)

print("Duplicate player-season combinations:")
print(player_stats_duplicates.shape)

player_stats_duplicates.head()

Duplicate player-season combinations:
(0, 3)

shape: (0, 3)
┌─────────┬────────┬─────┐
│ gsis_id ┆ season ┆ len │
│ ---     ┆ ---    ┆ --- │
│ str     ┆ i32    ┆ u32 │
╞═════════╪════════╪═════╡
└─────────┴────────┴─────┘

In [114]:
# Checking for any missing values in the WR player statistics dataframe

player_stats_missing = wr_player_stats.select([
    pl.col(column).null_count().alias(column)
    for column in wr_player_stats.columns
]).transpose(
    include_header=True,
    header_name="column",
    column_names=["missing_count"]
).sort(
    "missing_count",
    descending=True
)

player_stats_missing

shape: (29, 2)
┌─────────────────────┬───────────────┐
│ column              ┆ missing_count │
│ ---                 ┆ ---           │
│ str                 ┆ u32           │
╞═════════════════════╪═══════════════╡
│ receiving_epa       ┆ 13            │
│ racr                ┆ 13            │
│ gsis_id             ┆ 0             │
│ player_name         ┆ 0             │
│ player_display_name ┆ 0             │
│ …                   ┆ …             │
│ target_share        ┆ 0             │
│ air_yards_share     ┆ 0             │
│ wopr                ┆ 0             │
│ fantasy_points      ┆ 0             │
│ fantasy_points_ppr  ┆ 0             │
└─────────────────────┴───────────────┘

## Player Contracts Cleaning

We will follow a very similar process as we did for the Player Stats Cleanup since we plan on joining the data we must make sure everything aligns well

In [115]:
# Creating a subset of the WR contracts dataframe with only the columns of interest for analysis

wr_contracts_clean = wr_contracts.select([
    "player",
    "position",
    "team",
    "is_active",
    "year_signed",
    "years",
    "value",
    "apy",
    "guaranteed",
    "apy_cap_pct",
    "inflated_value",
    "inflated_apy",
    "inflated_guaranteed",
    "gsis_id",
    "college",
    "draft_year",
    "draft_team"
])

In [116]:
# Cleaning the gsis_id column in the WR contracts dataframe by stripping any leading or trailing whitespace characters

wr_contracts_clean = wr_contracts_clean.filter(
    pl.col("gsis_id").is_not_null() &
    (pl.col("gsis_id").str.strip_chars() != "")
)

In [117]:
wr_contracts_clean = wr_contracts_clean.with_columns(
    pl.col("gsis_id")
      .str.strip_chars()
      .alias("gsis_id")
)

In [118]:
# Checking for any missing or blank GSIS IDs in the WR contracts dataframe

print("Contract rows after GSIS ID cleaning:",
      wr_contracts_clean.height)

print(
    "Missing GSIS IDs:",
    wr_contracts_clean
    .select(pl.col("gsis_id").is_null().sum())
    .item()
)

print(
    "Blank GSIS IDs:",
    wr_contracts_clean
    .filter(pl.col("gsis_id") == "")
    .height
)

Contract rows after GSIS ID cleaning: 6772
Missing GSIS IDs: 0
Blank GSIS IDs: 0

In [119]:
# Checking for any missing values in the WR contracts dataframe

contract_missing = wr_contracts_clean.select([
    pl.col(column).null_count().alias(column)
    for column in wr_contracts_clean.columns
]).transpose(
    include_header=True,
    header_name="column",
    column_names=["missing_count"]
).sort(
    "missing_count",
    descending=True
)

contract_missing

shape: (17, 2)
┌─────────────────────┬───────────────┐
│ column              ┆ missing_count │
│ ---                 ┆ ---           │
│ str                 ┆ u32           │
╞═════════════════════╪═══════════════╡
│ draft_team          ┆ 209           │
│ college             ┆ 121           │
│ draft_year          ┆ 109           │
│ player              ┆ 0             │
│ position            ┆ 0             │
│ …                   ┆ …             │
│ apy_cap_pct         ┆ 0             │
│ inflated_value      ┆ 0             │
│ inflated_apy        ┆ 0             │
│ inflated_guaranteed ┆ 0             │
│ gsis_id             ┆ 0             │
└─────────────────────┴───────────────┘

## Joining the Stats and Contracts data

Now that both dataframes were cleaned and we have a working subset for each. We need to be able to join the two together so we can run exploratory analysis among the whole library of data

In [120]:
# Selecting relevant columns from the players dataframe to create a bridge for merging with player statistics and contracts data

player_id_bridge = players.select([
    "gsis_id",
    "display_name",
    "position",
    "position_group",
    "birth_date",
    "rookie_season",
    "last_season",
    "years_of_experience",
    "latest_team",
    "nfl_id",
    "pfr_id",
    "otc_id",
    "espn_id"
])

In [121]:
# Cleaning the gsis_id column in the player_id_bridge dataframe by stripping any leading or trailing whitespace characters and filtering out null or empty values

player_id_bridge = player_id_bridge.with_columns(
    pl.col("gsis_id")
      .str.strip_chars()
      .alias("gsis_id")
).filter(
    pl.col("gsis_id").is_not_null() &
    (pl.col("gsis_id") != "")
)

In [122]:
# Checking whether the bridge gsis_id column has any duplicate values, which could indicate potential issues with the player metadata

duplicate_bridge_ids = (
    player_id_bridge
    .group_by("gsis_id")
    .len()
    .filter(pl.col("len") > 1)
)

print("Duplicated GSIS IDs in player metadata:",
      duplicate_bridge_ids.height)

Duplicated GSIS IDs in player metadata: 0

In [123]:
# Joining the WR player statistics dataframe with the player metadata bridge on the gsis_id column to enrich the player statistics with additional player information

wr_stats_with_players = wr_player_stats.join(
    player_id_bridge,
    on="gsis_id",
    how="left",
    validate="m:1"
)

In [124]:
# Check whether all of the data was matched to players in the bridge by counting the number of rows with null display_name values

stats_identifier_validation = wr_stats_with_players.select([
    pl.len().alias("wr_stat_rows"),
    pl.col("display_name").is_not_null().sum().alias("matched_to_players"),
    pl.col("display_name").is_null().sum().alias("not_matched_to_players")
])

stats_identifier_validation

shape: (1, 3)
┌──────────────┬────────────────────┬────────────────────────┐
│ wr_stat_rows ┆ matched_to_players ┆ not_matched_to_players │
│ ---          ┆ ---                ┆ ---                    │
│ u32          ┆ u32                ┆ u32                    │
╞══════════════╪════════════════════╪════════════════════════╡
│ 235          ┆ 235                ┆ 0                      │
└──────────────┴────────────────────┴────────────────────────┘

In [125]:
# Joining the dataframes of WR contracts and WR player statistics (with player metadata) on the gsis_id column to create a combined dataset for analysis. The join is performed as a left join to retain all records from the WR contracts dataframe, while adding relevant statistics from the WR player statistics dataframe.

wr_contract_stat_history = (
    wr_contracts_clean
    .join(
        wr_stats_with_players,
        on="gsis_id",
        how="left",
        suffix="_stats"
    )
    .filter(
        pl.col("season") < pl.col("year_signed")
    )
)

In [126]:
# Retaining the most recent season before signing a contract for each player by sorting the combined dataframe and grouping by relevant columns, then selecting the last row in each group
# Taking a look at a players stats previous to signing a new contract will show the best connection of a players stats to how they are compensated

wr_contract_prior_season = (
    wr_contract_stat_history
    .sort([
        "gsis_id",
        "year_signed",
        "season"
    ])
    .group_by([
        "gsis_id",
        "year_signed",
        "team",
        "years",
        "value",
        "apy"
    ])
    .tail(1)
)

In [127]:
# Checking to see that the join was successful and that the most recent season prior to signing a contract was retained for each player by selecting relevant columns and sorting by year_signed in descending order, then displaying the top 20 rows

wr_contract_prior_season.select([
    "player",
    "gsis_id",
    "year_signed",
    "season",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "value",
    "apy",
    "guaranteed"
]).sort(
    "year_signed",
    descending=True
).head(20)

shape: (20, 11)
┌─────────────┬────────────┬─────────────┬────────┬───┬─────────────┬────────┬────────┬────────────┐
│ player      ┆ gsis_id    ┆ year_signed ┆ season ┆ … ┆ receiving_t ┆ value  ┆ apy    ┆ guaranteed │
│ ---         ┆ ---        ┆ ---         ┆ ---    ┆   ┆ ds          ┆ ---    ┆ ---    ┆ ---        │
│ str         ┆ str        ┆ i32         ┆ i32    ┆   ┆ ---         ┆ f64    ┆ f64    ┆ f64        │
│             ┆            ┆             ┆        ┆   ┆ i32         ┆        ┆        ┆            │
╞═════════════╪════════════╪═════════════╪════════╪═══╪═════════════╪════════╪════════╪════════════╡
│ Dyami Brown ┆ 00-0036626 ┆ 2026        ┆ 2024   ┆ … ┆ 1           ┆ 1.75   ┆ 1.75   ┆ 0.25       │
│ Michael     ┆ 00-0036252 ┆ 2026        ┆ 2024   ┆ … ┆ 3           ┆ 35.0   ┆ 17.5   ┆ 24.0       │
│ Pittman,    ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
│ Jr.         ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
│ JuJu Smith- ┆ 00-0033857 ┆ 2026        ┆ 2024   ┆ … ┆ 2           ┆ 1.3    ┆ 1.3    ┆ 0.0        │
│ Schuster    ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
│ John        ┆ 00-0037614 ┆ 2026        ┆ 2024   ┆ … ┆ 1           ┆ 1.9    ┆ 1.9    ┆ 1.0        │
│ Metchie III ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
│ Jalen       ┆ 00-0036387 ┆ 2026        ┆ 2024   ┆ … ┆ 0           ┆ 1.215  ┆ 1.215  ┆ 0.0        │
│ Reagor      ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
│ …           ┆ …          ┆ …           ┆ …      ┆ … ┆ …           ┆ …      ┆ …      ┆ …          │
│ Nico        ┆ 00-0036554 ┆ 2026        ┆ 2024   ┆ … ┆ 7           ┆ 60.0   ┆ 30.0   ┆ 57.0       │
│ Collins     ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
│ Tom Kennedy ┆ 00-0035544 ┆ 2026        ┆ 2024   ┆ … ┆ 0           ┆ 1.235  ┆ 1.235  ┆ 0.02       │
│ Jake Bobo   ┆ 00-0038752 ┆ 2026        ┆ 2024   ┆ … ┆ 1           ┆ 5.5    ┆ 2.75   ┆ 4.5        │
│ Simi Fehoko ┆ 00-0036646 ┆ 2026        ┆ 2024   ┆ … ┆ 0           ┆ 1.4025 ┆ 1.4025 ┆ 1.2625     │
│ Van         ┆ 00-0036415 ┆ 2026        ┆ 2024   ┆ … ┆ 2           ┆ 1.4025 ┆ 1.4025 ┆ 0.5275     │
│ Jefferson   ┆            ┆             ┆        ┆   ┆             ┆        ┆        ┆            │
└─────────────┴────────────┴─────────────┴────────┴───┴─────────────┴────────┴────────┴────────────┘

In [128]:
# Loading player statistics for a range of seasons

player_stats = nfl.load_player_stats(
    seasons=list(range(2010, 2026)),
    summary_level="reg"
)

player_stats.head(20)

shape: (20, 143)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-000004 ┆ F.Adams   ┆ Flozell   ┆ OT       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆ Adams     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000010 ┆ D.Akers   ┆ David     ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 8         ┆           ┆ Akers     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000055 ┆ B.Ayanbad ┆ Brendon   ┆ ILB      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 1         ┆ ejo       ┆ Ayanbadej ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ o         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000058 ┆ C.Bailey  ┆ Champ     ┆ CB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆ Bailey    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000074 ┆ R.Barber  ┆ Ronde     ┆ FS       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 1         ┆           ┆ Barber    ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-000303 ┆ D.Clark   ┆ Desmond   ┆ TE       ┆ … ┆ 0         ┆ 0         ┆ 1.2       ┆ 2.2       │
│ 5         ┆           ┆ Clark     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000329 ┆ K.Collins ┆ Kerry     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 109.02    ┆ 109.02    │
│ 2         ┆           ┆ Collins   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000331 ┆ T.Collins ┆ Todd      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ -7.28     ┆ -7.28     │
│ 5         ┆           ┆ Collins   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000387 ┆ P.Daniels ┆ Phillip   ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 4         ┆           ┆ Daniels   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-000407 ┆ B.Dawkins ┆ Brian     ┆ S        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Dawkins   ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Now that the Player Stats and Player Contracts data were successfuly joined there are a few things that need to be done before continuing...

- We must agree on how to fill in missing values from the stats and contracts data
- Figure out how to check for duplicate contract data since one GSIS ID can have multiple contracts

Once this is all done we should be set to start Exploratory Analysis with our target variable as receiving yards. We will predict receiving yards for a player in a season and then assess what their value should be based on the predicted stats

## Exploratory Analysis

Briefly laying the outline for how we will start the modeling of NFL Wide Receiver Receiving Yards. We start out small by getting summary statistics and finding correlation between variables. We will take a look at player stats first to predict receiving yards befoe incorporating the contract data

In [129]:
# Summary statistics for the WR player statistics dataframe, including measures such as count, mean, standard deviation, minimum, maximum, and quartiles for selected columns related to receiving performance and fantasy points

summary_statistics = (
    wr_stats_with_players
    .select([
        "games",
        "receptions",
        "targets",
        "receiving_yards",
        "receiving_tds",
        "receiving_air_yards",
        "receiving_yards_after_catch",
        "receiving_first_downs",
        "target_share",
        "fantasy_points_ppr"
    ])
    .describe()
)

summary_statistics

shape: (9, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ games    ┆ reception ┆ targets   ┆ … ┆ receiving ┆ receiving ┆ target_sh ┆ fantasy_p │
│ ---       ┆ ---      ┆ s         ┆ ---       ┆   ┆ _yards_af ┆ _first_do ┆ are       ┆ oints_ppr │
│ str       ┆ f64      ┆ ---       ┆ f64       ┆   ┆ ter_catch ┆ wns       ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆           ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 235.0    ┆ 235.0     ┆ 235.0     ┆ … ┆ 235.0     ┆ 235.0     ┆ 235.0     ┆ 235.0     │
│ null_coun ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 10.32766 ┆ 27.612766 ┆ 43.412766 ┆ … ┆ 123.33617 ┆ 16.506383 ┆ 0.081636  ┆ 77.40017  │
│ std       ┆ 5.33244  ┆ 29.428296 ┆ 44.223933 ┆ … ┆ 148.58745 ┆ 17.984174 ┆ 0.082189  ┆ 83.814558 │
│           ┆          ┆           ┆           ┆   ┆ 8         ┆           ┆           ┆           │
│ min       ┆ 1.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ -0.4      │
│ 25%       ┆ 5.0      ┆ 3.0       ┆ 5.0       ┆ … ┆ 10.0      ┆ 2.0       ┆ 0.009579  ┆ 7.1       │
│ 50%       ┆ 12.0     ┆ 17.0      ┆ 29.0      ┆ … ┆ 71.0      ┆ 9.0       ┆ 0.051756  ┆ 41.9      │
│ 75%       ┆ 15.0     ┆ 45.0      ┆ 71.0      ┆ … ┆ 183.0     ┆ 28.0      ┆ 0.132383  ┆ 126.0     │
│ max       ┆ 17.0     ┆ 127.0     ┆ 175.0     ┆ … ┆ 787.0     ┆ 75.0      ┆ 0.306859  ┆ 403.0     │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [130]:
# Correlation analysis for selected variables in the WR player statistics dataframe to examine the relationships between different performance metrics and fantasy points
# The most important column to note here is the receiving yards.

correlation_variables = [

    "games",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "target_share",
    "fantasy_points_ppr"

]

correlation_df = (
    wr_stats_with_players
    .select(correlation_variables)
    .to_pandas()
)

correlation_df.corr()

,games,receptions,targets,receiving_yards,receiving_tds,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,target_share,fantasy_points_ppr
games,1.000000,0.711644,0.732939,0.702498,0.595848,0.715674,0.637558,0.696910,0.739762,0.708322
receptions,0.711644,1.000000,0.987892,0.974105,0.831220,0.895504,0.905268,0.976439,0.979964,0.981272
targets,0.732939,0.987892,1.000000,0.971962,0.827155,0.939356,0.874003,0.971223,0.991543,0.974819
receiving_yards,0.702498,0.974105,0.971962,1.000000,0.864273,0.936902,0.891507,0.983879,0.971666,0.991165
receiving_tds,0.595848,0.831220,0.827155,0.864273,1.000000,0.813549,0.748097,0.865545,0.826305,0.905376
receiving_air_yards,0.715674,0.895504,0.939356,0.936902,0.813549,1.000000,0.731249,0.925757,0.940027,0.920998
receiving_yards_after_catch,0.637558,0.905268,0.874003,0.891507,0.748097,0.731249,1.000000,0.858337,0.870257,0.899350
receiving_first_downs,0.696910,0.976439,0.971223,0.983879,0.865545,0.925757,0.858337,1.000000,0.967493,0.983614
target_share,0.739762,0.979964,0.991543,0.971666,0.826305,0.940027,0.870257,0.967493,1.000000,0.971445
fantasy_points_ppr,0.708322,0.981272,0.974819,0.991165,0.905376,0.920998,0.899350,0.983614,0.971445,1.000000